// COE224: Assembly Language Studio - Instruction Hover Tooltips Database

import { InstructionTooltip } from '../engine/types';

export const INSTRUCTION_TOOLTIPS: Record<string, InstructionTooltip> = {
  mov: {
    name: 'MOV — Move Data',
    description: 'Copies data from a source operand into a destination operand.',
    syntax: ['MOV reg, reg/mem/imm', 'MOV mem, reg/imm'],
    flagsAffected: 'None',
    tip: 'Cannot move memory-to-memory. Operands must be the same size.',
    chapter: 4,
  },
  movzx: {
    name: 'MOVZX — Move with Zero-Extend',
    description: 'Copies a smaller unsigned value into a larger register, filling upper bits with zeros.',
    syntax: ['MOVZX reg32, reg8/mem8', 'MOVZX reg32, reg16/mem16'],
    flagsAffected: 'None',
    tip: 'Useful when promoting an 8-bit or 16-bit unsigned number to 32 bits.',
    chapter: 4,
  },
  movsx: {
    name: 'MOVSX — Move with Sign-Extend',
    description: 'Copies a smaller signed value into a larger register, replicating the sign bit into upper bits.',
    syntax: ['MOVSX reg32, reg8/mem8', 'MOVSX reg32, reg16/mem16'],
    flagsAffected: 'None',
    tip: 'Preserves the signed 2\'s complement value during widening.',
    chapter: 4,
  },
  xchg: {
    name: 'XCHG — Exchange Register/Memory with Register',
    description: 'Swaps the contents of two operands atomically without an intermediate variable.',
    syntax: ['XCHG reg, reg', 'XCHG reg, mem', 'XCHG mem, reg'],
    flagsAffected: 'None',
    tip: 'Neither operand can be an immediate constant.',
    chapter: 4,
  },
  add: {
    name: 'ADD — Add Integers',
    description: 'Adds the source operand to the destination operand and stores the sum in destination.',
    syntax: ['ADD reg, reg/mem/imm', 'ADD mem, reg/imm'],
    flagsAffected: 'CF, ZF, SF, OF, AF, PF',
    tip: 'Sets CF on unsigned carry, OF on signed 2\'s complement overflow.',
    chapter: 4,
  },
  sub: {
    name: 'SUB — Subtract Integers',
    description: 'Subtracts the source operand from the destination operand (dest = dest - src).',
    syntax: ['SUB reg, reg/mem/imm', 'SUB mem, reg/imm'],
    flagsAffected: 'CF, ZF, SF, OF, AF, PF',
    tip: 'Sets CF on unsigned borrow (dest < src), OF on signed underflow.',
    chapter: 4,
  },
  cmp: {
    name: 'CMP — Compare Operands',
    description: 'Computes (dest - src) and updates EFLAGS without modifying either operand.',
    syntax: ['CMP reg, reg/mem/imm', 'CMP mem, reg/imm'],
    flagsAffected: 'CF, ZF, SF, OF, AF, PF',
    tip: 'Use immediately before conditional jumps (JE, JNE, JA, JB, JG, JL).',
    chapter: 6,
  },
  inc: {
    name: 'INC — Increment by 1',
    description: 'Adds 1 to destination operand.',
    syntax: ['INC reg', 'INC mem'],
    flagsAffected: 'ZF, SF, OF, AF, PF (CF is NOT affected!)',
    tip: 'Important: INC preserves the Carry Flag (CF).',
    chapter: 4,
  },
  dec: {
    name: 'DEC — Decrement by 1',
    description: 'Subtracts 1 from destination operand.',
    syntax: ['DEC reg', 'DEC mem'],
    flagsAffected: 'ZF, SF, OF, AF, PF (CF is NOT affected!)',
    tip: 'Important: DEC preserves the Carry Flag (CF).',
    chapter: 4,
  },
  neg: {
    name: 'NEG — Two\'s Complement Negation',
    description: 'Reverses the arithmetic sign of an integer (dest = 0 - dest).',
    syntax: ['NEG reg', 'NEG mem'],
    flagsAffected: 'CF, ZF, SF, OF, AF, PF',
    tip: 'Sets CF=1 for any non-zero value; sets OF=1 if negating the maximum negative value.',
    chapter: 4,
  },
  push: {
    name: 'PUSH — Push onto Stack',
    description: 'Decrements ESP by 4, then writes the 32-bit operand to memory at [ESP].',
    syntax: ['PUSH reg32', 'PUSH mem32', 'PUSH imm32'],
    flagsAffected: 'None',
    tip: 'Stack grows downward toward lower memory addresses.',
    chapter: 5,
  },
  pop: {
    name: 'POP — Pop from Stack',
    description: 'Reads the 32-bit value at [ESP] into destination, then increments ESP by 4.',
    syntax: ['POP reg32', 'POP mem32'],
    flagsAffected: 'None',
    tip: 'Operand cannot be an immediate value.',
    chapter: 5,
  },
  call: {
    name: 'CALL — Call Procedure',
    description: 'Pushes the address of the next instruction onto stack, then transfers control to procedure.',
    syntax: ['CALL targetLabel'],
    flagsAffected: 'None',
    tip: 'Every CALL must be matched by a RET in the procedure.',
    chapter: 5,
  },
  ret: {
    name: 'RET — Return from Procedure',
    description: 'Pops the return address from the stack into EIP and resumes execution in the caller.',
    syntax: ['RET'],
    flagsAffected: 'None',
    tip: 'Ensure the stack is balanced (all PUSHes popped) before calling RET.',
    chapter: 5,
  },
  jmp: {
    name: 'JMP — Unconditional Jump',
    description: 'Transfers program execution unconditionally to the target label.',
    syntax: ['JMP targetLabel'],
    flagsAffected: 'None',
    tip: 'Directly changes EIP.',
    chapter: 6,
  },
  loop: {
    name: 'LOOP — Loop According to ECX',
    description: 'Decrements ECX by 1; if ECX != 0, jumps to target label. Does NOT modify flags.',
    syntax: ['LOOP targetLabel'],
    flagsAffected: 'None',
    tip: 'Load loop count into ECX before entering the loop.',
    chapter: 6,
  },
  shl: {
    name: 'SHL — Shift Logical Left',
    description: 'Shifts bits to the left, filling low bits with 0. Outgoing bit enters CF.',
    syntax: ['SHL reg, imm8/CL', 'SHL mem, imm8/CL'],
    flagsAffected: 'CF, OF, SF, ZF, PF',
    tip: 'Shifting left by n bits multiplies an unsigned integer by 2^n.',
    chapter: 7,
  },
  shr: {
    name: 'SHR — Shift Logical Right',
    description: 'Shifts bits to the right, filling high bits with 0. Outgoing bit enters CF.',
    syntax: ['SHR reg, imm8/CL', 'SHR mem, imm8/CL'],
    flagsAffected: 'CF, OF, SF, ZF, PF',
    tip: 'Shifting right by n bits divides an unsigned integer by 2^n.',
    chapter: 7,
  },
  mul: {
    name: 'MUL — Unsigned Multiply',
    description: 'Multiplies AL/AX/EAX by source operand. 32-bit result is placed in EDX:EAX.',
    syntax: ['MUL reg/mem'],
    flagsAffected: 'CF, OF (set if high half is non-zero)',
    tip: 'Single operand syntax; AL/AX/EAX is the implicit multiplicand.',
    chapter: 7,
  },
  div: {
    name: 'DIV — Unsigned Divide',
    description: 'Divides AX (16-bit), DX:AX (32-bit), or EDX:EAX (64-bit) by source operand.',
    syntax: ['DIV reg/mem'],
    flagsAffected: 'Undefined',
    tip: 'Quotient stored in EAX, remainder in EDX. Divisor cannot be 0.',
    chapter: 7,
  },
};
